GET http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNtYW4iLCJpYXQiOjE2ODU4NjEzMDd9.n95HR8NTJ5TGqGn3iiwdt0nKyjtx9we0iX-9SXWeypo

### 
GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNtYW4iLCJpYXQiOjE2ODU4NjEzMDd9.n95HR8NTJ5TGqGn3iiwdt0nKyjtx9we0iX-9SXWeypo


###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"mahir"
}

###

GET http://localhost:3002/channel-participants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFoaXIiLCJpYXQiOjE2ODYwNDM3MzN9.a-x8h_Z8uhAknuXWfWNePUVQXxQGduD0QMVNkajrkdQ

###
POST http://localhost:3002/channel-messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFoaXIiLCJpYXQiOjE2ODYyODk3OTN9.6TsrsFM4tVvSgYuCSw2l6FxmpS5v_w6Lgq8U7qnegMo

{
    "channel_id" : "7898asubdasd"
}

###
POST http://localhost:3002/get-channel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFoaXIiLCJpYXQiOjE2ODYwNjE3NDd9.pRYGNNqmSGvYNmmWmpGrFpmwMPnOlBN2GwZwYzHLIXE

{
    "channel_id" : "7898asubdasd"
}

###

POST link
Content-Type: application/json

{
    "name":"mahir"
}

###

POST http://localhost:3002/send-message
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFoaXIiLCJpYXQiOjE2ODYzNzg2NDN9.XMOhs4cd76sy5VmIjSGZDL0TSnL7GJhqkpdU0Omk5NM

{
    "channel_id":"7898asubdasd2", 
    "content":"test 1", 
    "timestamp":1234567876543
}